feat(cb2-6757): test records flow submit
dvsa/cvs-app-vtm pull request #674
Opened 2022-11-16 14:49 UTC by Ruairidh-BJSS

Add check answers page to view the test result before submitting

https://dvsa.atlassian.net/browse/CB2-6757

## Checklist

- [ ] Branch is rebased against the latest develop/common
- [ ] Necessary `id` required prepended with `"test-"` have been checked with automation testers and added
- [ ] Code and UI has been tested manually after the additional changes
- [ ] PR title includes the JIRA ticket number
- [ ] Squashed commits contain the JIRA ticket number
- [ ] Link to the PR added to the repo
- [ ] Delete branch after merge

2022-11-16 15:09 UTC, mcadenas-bjss submitted a review, later dismissed

2022-11-16 15:12 UTC, kpearmanbjss submitted a review, later dismissed

2022-11-16 16:58 UTC, andrewf-bjss commented on src/app/features/test-records/components/base-test-record/base-test-record.component.ts
> +  @Input() isContingency = false;
Could we show this same review page for Test Result amendment as well?  (i.e. not just Contingency tests?)

2022-11-16 16:59 UTC, andrewf-bjss requested changes
Could we show this same review page for Test Result amendment as well? (i.e. not just Contingency tests?)

2022-11-17 09:44 UTC, kpearmanbjss submitted a review, later dismissed

2022-11-17 11:06 UTC, mcadenas-bjss submitted a review, later dismissed

2022-11-17 11:09 UTC, andrewf-bjss approved these changes
Thank you  🙂

2022-11-17 11:12 UTC, gjulien-bjss commented on src/app/features/test-records/create/views/create-test-record/create-test-record.component.ts
> +  }
why is this async?

2022-11-17 11:16 UTC, Ruairidh-BJSS commented
Not to be merged until after VTM cut

2022-11-18 13:02 UTC, mcadenas-bjss submitted a review, later dismissed

2022-11-18 14:49 UTC, tahayazici commented on src/app/features/test-records/amend/views/test-record/test-record.component.ts
> +      : (this.testMode = TestModeEnum.Cancel);
```suggestion
    this.testMode = this.testMode === TestModeEnum.Cancel || this.testMode === TestModeEnum.View
      ? TestModeEnum.Edit
      : TestModeEnum.Cancel;
```

2022-11-18 14:54 UTC, tahayazici commented on src/app/features/test-records/create/views/create-test-record/create-test-record.component.html
> +  <ng-container [ngSwitch]="testMode">
You can combine this and the above `<ng-container>`
```suggestion
<ng-container *ngIf="testResult$ | async as testResult" [ngSwitch]="testMode">
```

2022-11-18 16:01 UTC, mcadenas-bjss approved these changes

2022-11-18 16:07 UTC, tahayazici approved these changes

2022-11-18 16:12 UTC, merged